# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.BigIntegerField(default=None),
        ),
    ]
