# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161102_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_contact',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(choices=[(1, b'I'), (2, b'II'), (3, b'III'), (4, b'IV'), (5, b'V'), (6, b'VI'), (7, b'VII'), (8, b'VIII'), (9, b'IX'), (10, b'X')], default=None),
        ),
    ]
