# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161102_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
