# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161102_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default=b'', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default=b'', max_length=254),
        ),
    ]
